name: Build and Release Java JAR

on:
  push:
    tags:
      - 'v*.*.*'  # هر بار که تگ مثل v1.0.0 زده شد
  workflow_dispatch: # امکان اجرای دستی

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build JAR with Gradle
      run: ./gradlew clean build

    - name: Upload JAR to release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
